main.out:polynomial.o posynomial.o main.o func.h
	g++ polynomial.o posynomial.o main.o -o main.out
polynomial.o:polynomial.cpp func.h
	g++ -c polynomial.cpp -o polynomial.o
posynomial.o:posynomial.cpp func.h
	g++ -c posynomial.cpp -o posynomial.o
main.o:main.cpp func.h
	g++ -c main.cpp -o main.o
